In [8]:
import yaml
import pandas as pd
import requests

In [43]:
response=requests.get("https://datasets-server.huggingface.co/rows?dataset=cestwc%2Fbank-marketing&config=default&split=train&offset=0&length=100")

In [45]:
data_cols = response.json()

df_col_vals = pd.json_normalize(data_cols["features"])

df_col_vals = df_col_vals[["feature_idx", "name", "type.names"]]
df_col_vals

    feature_idx       name                                         type.names
0             0        age                                                NaN
1             1        job  [admin., blue-collar, entrepreneur, housemaid,...
2             2    marital               [divorced, married, single, unknown]
3             3  education  [primary, secondary, tertiary, unknown, basic....
4             4    default                                 [no, yes, unknown]
5             5    balance                                                NaN
6             6    housing                                 [no, yes, unknown]
7             7       loan                                 [no, yes, unknown]
8             8    contact                     [cellular, telephone, unknown]
9             9        day                                                NaN
10           10      month  [jan, feb, mar, apr, may, jun, jul, aug, sep, ...
11           11   duration                                                NaN
12           12   campaign                                                NaN
13           13      pdays                                                NaN
14           14   previous                                                NaN
15           15   poutcome    [failure, other, success, unknown, nonexistent]
16           16          y                                          [no, yes]

In [46]:
import requests
import pandas as pd

url = "https://huggingface.co/api/datasets/cestwc/bank-marketing/parquet/default/train"

response = requests.get(url)
files = response.json()

bf = pd.read_parquet(files[0])

In [47]:
bf

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,4,1,2,0,2143,1,0,2,5,4,261,1,999,0,3,0
1,44,9,2,1,0,29,1,0,2,5,4,151,1,999,0,3,0
2,33,2,1,1,0,2,1,1,2,5,4,76,1,999,0,3,0
3,47,1,1,3,0,1506,1,0,2,5,4,92,1,999,0,3,0
4,33,11,2,3,0,1,0,0,2,5,4,198,1,999,0,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,9,1,2,0,825,0,0,0,17,10,977,3,999,0,3,1
45207,71,5,0,0,0,1729,0,0,0,17,10,456,2,999,0,3,1
45208,72,5,1,1,0,5715,0,0,0,17,10,1127,5,184,3,2,1
45209,57,1,1,1,0,668,0,0,1,17,10,508,4,999,0,3,0
45210,37,2,1,1,0,2971,0,0,0,17,10,361,2,188,11,1,0

In [54]:
df_col_vals[df_col_vals['type.names'] != None]

    feature_idx       name                                         type.names
0             0        age                                                NaN
1             1        job  [admin., blue-collar, entrepreneur, housemaid,...
2             2    marital               [divorced, married, single, unknown]
3             3  education  [primary, secondary, tertiary, unknown, basic....
4             4    default                                 [no, yes, unknown]
5             5    balance                                                NaN
6             6    housing                                 [no, yes, unknown]
7             7       loan                                 [no, yes, unknown]
8             8    contact                     [cellular, telephone, unknown]
9             9        day                                                NaN
10           10      month  [jan, feb, mar, apr, may, jun, jul, aug, sep, ...
11           11   duration                                                NaN
12           12   campaign                                                NaN
13           13      pdays                                                NaN
14           14   previous                                                NaN
15           15   poutcome    [failure, other, success, unknown, nonexistent]
16           16          y                                          [no, yes]

In [58]:
df_col_vals = df_col_vals.dropna()

In [63]:
for _, row in df_col_vals.iterrows():
    col = row["name"]
    labels = row["type.names"]
    bf[col] = bf[col].map(dict(enumerate(labels)))

In [64]:
bf.columns

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'y'],
      dtype='str')

In [5]:
bf.isna().sum()

age               0
job               0
marital           0
education         0
default           0
housing           0
loan              0
contact           0
month             0
day_of_week       0
duration          0
campaign          0
pdays             0
previous          0
poutcome          0
emp.var.rate      0
cons.price.idx    0
cons.conf.idx     0
euribor3m         0
nr.employed       0
y                 0
dtype: int64

In [6]:
bf.dtypes

age                 int64
job                   str
marital               str
education             str
default               str
housing               str
loan                  str
contact               str
month                 str
day_of_week           str
duration            int64
campaign            int64
pdays               int64
previous            int64
poutcome              str
emp.var.rate      float64
cons.price.idx    float64
cons.conf.idx     float64
euribor3m         float64
nr.employed       float64
y                     str
dtype: object

In [7]:
bf.age.value_counts()
#bin later

age
31    1947
32    1846
33    1833
36    1780
35    1759
      ...
98       2
89       2
95       1
87       1
94       1
Name: count, Length: 78, dtype: int64

In [8]:
bf.job.value_counts()

job
admin.           10422
blue-collar       9254
technician        6743
services          3969
management        2924
retired           1720
entrepreneur      1456
self-employed     1421
housemaid         1060
unemployed        1014
student            875
unknown            330
Name: count, dtype: int64

In [9]:
bf.marital.value_counts()

marital
married     24928
single      11568
divorced     4612
unknown        80
Name: count, dtype: int64

In [10]:
bf.default.value_counts()

default
no         32588
unknown     8597
yes            3
Name: count, dtype: int64

In [11]:
bf.balance.value_counts()

AttributeError: 'DataFrame' object has no attribute 'balance'

In [ ]:
bf.housing.value_counts()

In [ ]:
bf.loan.value_counts()

In [ ]:
bf.contact.value_counts()

In [ ]:
bf.contact.value_counts()

In [ ]:
bf.day.value_counts()

In [ ]:
bf.month.value_counts()

In [ ]:
bf.duration.value_counts()
#this shouldn't be used in a predictive model, as it is not known before contacting the customer

In [ ]:
bf.campaign.value_counts()
#needs to be binned

In [ ]:
bf.pdays.value_counts(), bf.pdays.nunique()
#-1 means never been contacted

In [ ]:
bf['previously_contacted']= bf.pdays.apply([lambda x: 0 if x==-1 else 1])

In [ ]:
bf['previously_contacted'].value_counts()

In [ ]:
bf.pdays.max()

In [ ]:
bf.previous.value_counts()
#needs to be binned

In [ ]:
bf.poutcome.value_counts()

In [ ]:
bf.y.value_counts()

In [ ]:
bf.columns

In [ ]:
bf.to_csv("../data/clean/bank-full.csv", index=False, encoding= "utf-8", sep = ";")