In [1]:
import yaml
import pandas as pd

In [2]:
with open("../config.yaml",'r') as file:
    config = yaml.safe_load(file)

In [3]:
config

{'data': {'raw': {'file1': '../data/raw/LeadScoring.csv',
   'file2': '../data/raw/Leads_Data_Dictionary.csv',
   'file3': '../data/raw/digital_marketing_campaign_dataset.csv',
   'file4': '../data/raw/bank.csv',
   'file5': '../data/raw/bank-full.csv',
   'file6': '../data/raw/bank-additional.csv',
   'file7': '../data/raw/bank-additional-full.csv'},
  'clean': {'file1': '../data/clean/leadscoring.csv',
   'file2': '../data/clean/bank-full.csv',
   'file3': '../data/clean/ready_to_model.csv'}}}

In [4]:
data = pd.read_csv(config['data']['raw']['file1'], quotechar='"', sep = ",")

In [5]:
data.columns

Index(['Prospect ID', 'Lead Number', 'Lead Origin', 'Lead Source',
       'Do Not Email', 'Do Not Call', 'Converted', 'TotalVisits',
       'Total Time Spent on Website', 'Page Views Per Visit', 'Last Activity',
       'Country', 'Specialization', 'How did you hear about X Education',
       'What is your current occupation',
       'What matters most to you in choosing a course', 'Search', 'Magazine',
       'Newspaper Article', 'X Education Forums', 'Newspaper',
       'Digital Advertisement', 'Through Recommendations',
       'Receive More Updates About Our Courses', 'Tags', 'Lead Quality',
       'Update me on Supply Chain Content', 'Get updates on DM Content',
       'Lead Profile', 'City', 'Asymmetrique Activity Index',
       'Asymmetrique Profile Index', 'Asymmetrique Activity Score',
       'Asymmetrique Profile Score',
       'I agree to pay the amount through cheque',
       'A free copy of Mastering The Interview', 'Last Notable Activity'],
      dtype='str')

In [6]:
data.head(5)

,Prospect ID,Lead Number,Lead Origin,Lead Source,Do Not Email,Do Not Call,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,...,Get updates on DM Content,Lead Profile,City,Asymmetrique Activity Index,Asymmetrique Profile Index,Asymmetrique Activity Score,Asymmetrique Profile Score,I agree to pay the amount through cheque,A free copy of Mastering The Interview,Last Notable Activity
0,7927b2df-8bba-4d29-b9a2-b6e0beafe620,660737,API,Olark Chat,No,No,0,0.0,0,0.0,...,No,Select,Select,02.Medium,02.Medium,15.0,15.0,No,No,Modified
1,2a272436-5132-4136-86fa-dcc88c88f482,660728,API,Organic Search,No,No,0,5.0,674,2.5,...,No,Select,Select,02.Medium,02.Medium,15.0,15.0,No,No,Email Opened
2,8cc8c611-a219-4f35-ad23-fdfd2656bd8a,660727,Landing Page Submission,Direct Traffic,No,No,1,2.0,1532,2.0,...,No,Potential Lead,Mumbai,02.Medium,01.High,14.0,20.0,No,Yes,Email Opened
3,0cc2df48-7cf4-4e39-9de9-19797f9b38cc,660719,Landing Page Submission,Direct Traffic,No,No,0,1.0,305,1.0,...,No,Select,Mumbai,02.Medium,01.High,13.0,17.0,No,No,Modified
4,3256f628-e534-4826-9d63-4a8b88782852,660681,Landing Page Submission,Google,No,No,1,2.0,1428,1.0,...,No,Select,Mumbai,02.Medium,01.High,15.0,18.0,No,No,Modified

In [60]:
data.nunique()

Prospect ID                                      9240
Lead Number                                      9240
Lead Origin                                         5
Lead Source                                        21
Do Not Email                                        2
Do Not Call                                         2
Converted                                           2
TotalVisits                                        41
Total Time Spent on Website                      1731
Page Views Per Visit                              114
Last Activity                                      17
Country                                            38
Specialization                                     19
How did you hear about X Education                 10
What is your current occupation                     6
What matters most to you in choosing a course       3
Search                                              2
Magazine                                            1
Newspaper Article                                   2
X Education Forums                                  2
Newspaper                                           2
Digital Advertisement                               2
Through Recommendations                             2
Receive More Updates About Our Courses              1
Tags                                               26
Lead Quality                                        5
Update me on Supply Chain Content                   1
Get updates on DM Content                           1
Lead Profile                                        6
City                                                7
Asymmetrique Activity Index                         3
Asymmetrique Profile Index                          3
Asymmetrique Activity Score                        12
Asymmetrique Profile Score                         10
I agree to pay the amount through cheque            1
A free copy of Mastering The Interview              2
Last Notable Activity                              16
dtype: int64

In [73]:
def clean_col_names(df):
    """
    Updates column names to remove spaces and make lower case
    INPUT: complete dataframe
    OUTPUT: complete dataframe with new col names
    """
    df2 = df.copy()
    df2.columns = df2.columns.map(lambda x: x.lower().replace(' ','_'))
    return df2

def rename_cols(df):
    df2 = df.copy()
    df2 = df2.rename(columns={"total_time_spent_on_website": "time_on_website", 
                        "how_did_you_hear_about_x_education": "heard_about_x_ed",
               "what_is_your_current_occupation":"current_occupation",
               "what_matters_most_to_you_in_choosing_a_course":"most_imp_factor","receive_more_updates_about_our_courses":"get_updates",
               "i_agree_to_pay_the_amount_through_cheque": "pay_by_cheque" ,"a_free_copy_of_mastering_the_interview":"interview_ebook",
              "update_me_on_supply_chain_content":"supply_chain_updates"})
    return df2

In [74]:
data = clean_col_names(data)
data.columns
data = rename_cols(data)

In [75]:
data.dtypes

prospect_id                        str
lead_number                      int64
lead_origin                        str
lead_source                        str
do_not_email                       str
do_not_call                        str
converted                        int64
totalvisits                    float64
time_on_website                  int64
page_views_per_visit           float64
last_activity                      str
country                            str
specialization                     str
heard_about_x_ed                   str
current_occupation                 str
most_imp_factor                    str
search                             str
magazine                           str
newspaper_article                  str
x_education_forums                 str
newspaper                          str
digital_advertisement              str
through_recommendations            str
get_updates                        str
tags                               str
lead_quality                       str
supply_chain_updates               str
get_updates_on_dm_content          str
lead_profile                       str
city                               str
asymmetrique_activity_index        str
asymmetrique_profile_index         str
asymmetrique_activity_score    float64
asymmetrique_profile_score     float64
pay_by_cheque                      str
interview_ebook                    str
last_notable_activity              str
dtype: object

In [79]:
data.drop(columns=["asymmetrique_activity_index","asymmetrique_profile_index","asymmetrique_activity_score","asymmetrique_profile_score"])

,prospect_id,lead_number,lead_origin,lead_source,do_not_email,do_not_call,converted,totalvisits,time_on_website,page_views_per_visit,...,get_updates,tags,lead_quality,supply_chain_updates,get_updates_on_dm_content,lead_profile,city,pay_by_cheque,interview_ebook,last_notable_activity
0,7927b2df-8bba-4d29-b9a2-b6e0beafe620,660737,API,Olark Chat,No,No,0,0.0,0,0.00,...,No,Interested in other courses,Low in Relevance,No,No,Select,Select,No,No,Modified
1,2a272436-5132-4136-86fa-dcc88c88f482,660728,API,Organic Search,No,No,0,5.0,674,2.50,...,No,Ringing,NaN,No,No,Select,Select,No,No,Email Opened
2,8cc8c611-a219-4f35-ad23-fdfd2656bd8a,660727,Landing Page Submission,Direct Traffic,No,No,1,2.0,1532,2.00,...,No,Will revert after reading the email,Might be,No,No,Potential Lead,Mumbai,No,Yes,Email Opened
3,0cc2df48-7cf4-4e39-9de9-19797f9b38cc,660719,Landing Page Submission,Direct Traffic,No,No,0,1.0,305,1.00,...,No,Ringing,Not Sure,No,No,Select,Mumbai,No,No,Modified
4,3256f628-e534-4826-9d63-4a8b88782852,660681,Landing Page Submission,Google,No,No,1,2.0,1428,1.00,...,No,Will revert after reading the email,Might be,No,No,Select,Mumbai,No,No,Modified
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9235,19d6451e-fcd6-407c-b83b-48e1af805ea9,579564,Landing Page Submission,Direct Traffic,Yes,No,1,8.0,1845,2.67,...,No,Will revert after reading the email,High in Relevance,No,No,Potential Lead,Mumbai,No,No,Email Marked Spam
9236,82a7005b-7196-4d56-95ce-a79f937a158d,579546,Landing Page Submission,Direct Traffic,No,No,0,2.0,238,2.00,...,No,wrong number given,Might be,No,No,Potential Lead,Mumbai,No,Yes,SMS Sent
9237,aac550fe-a586-452d-8d3c-f1b62c94e02c,579545,Landing Page Submission,Direct Traffic,Yes,No,0,2.0,199,2.00,...,No,invalid number,Not Sure,No,No,Potential Lead,Mumbai,No,Yes,SMS Sent
9238,5330a7d1-2f2b-4df4-85d6-64ca2f6b95b9,579538,Landing Page Submission,Google,No,No,1,3.0,499,3.00,...,No,NaN,NaN,No,No,NaN,Other Metro Cities,No,No,SMS Sent
9239,571b5c8e-a5b2-4d57-8574-f2ffb06fdeff,579533,Landing Page Submission,Direct Traffic,No,No,1,6.0,1279,3.00,...,No,Will revert after reading the email,Might be,No,No,Potential Lead,Other Cities,No,Yes,Modified

In [80]:
data.to_csv("../data/clean/leadscoring.csv", index=False, encoding= "utf-8", sep = ";")